server:
  port: 22

spring:
  application:
    name: API-GATEWAY
#  Gateway Routes registration
  cloud:
    gateway:
      routes:
        - id: AUTHORIZATION-SERVER
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/oauth/**
        - id: RESOURCES-SERVER
          uri: lb://RESOURCES-SERVER
          predicates:
            - Path=/api/**
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

